// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75QpUELrU-jxvVA0FerhRQqtwb0Tbdgk',
    appId: '1:90618087933:web:e84ed5a8e9f436ebd13194',
    messagingSenderId: '90618087933',
    projectId: 'atelier-4-n-zaizi-iir5g2',
    authDomain: 'atelier-4-n-zaizi-iir5g2.firebaseapp.com',
    storageBucket: 'atelier-4-n-zaizi-iir5g2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLxyuJVulSoxhNxPi8piNwbVZ5cvWgA8U',
    appId: '1:90618087933:android:5244f046c6e8b33ed13194',
    messagingSenderId: '90618087933',
    projectId: 'atelier-4-n-zaizi-iir5g2',
    storageBucket: 'atelier-4-n-zaizi-iir5g2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJq-2ij8Ue-m_PjiXyb5_3t77BGtIvZTs',
    appId: '1:90618087933:ios:52c26a533c6c71c4d13194',
    messagingSenderId: '90618087933',
    projectId: 'atelier-4-n-zaizi-iir5g2',
    storageBucket: 'atelier-4-n-zaizi-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4NZaiziIir5g2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJq-2ij8Ue-m_PjiXyb5_3t77BGtIvZTs',
    appId: '1:90618087933:ios:1374e9a67189e4b4d13194',
    messagingSenderId: '90618087933',
    projectId: 'atelier-4-n-zaizi-iir5g2',
    storageBucket: 'atelier-4-n-zaizi-iir5g2.appspot.com',
    iosBundleId: 'com.example.atelier4NZaiziIir5g2.RunnerTests',
  );
}
